# These are supported funding model platforms

github: # [GitHub Sponsors page](https://github.com/sponsors/CoderBlee/dashboard)
buy_me_a_coffee: #Fuel my coding sessions by [buying me a coffee](https://buymeacoffee.com/gamu). ☕ Your support keeps the inspiration flowing
   
